### PR TITLE
Adapt FTS RFC for 3 new query types & advanced sorting.

### PR DESCRIPTION
**Pull request by daschl**
- Geo Distance
 - Geo Bounding Box
 - Term Range
 - Advanced Sorting

### CODE REVIEW

**Comment by daschl** [comment]
*note for myself*: there are also advanced sort options which should make it into here as well, will follow up on this.

**Comment by daschl** [comment]
@mschoch ready for re-review if you got couple minutes, this time including sorting

**Comment by daschl** [comment]
@couchbaselabs/sdk-team  heads up! 🔥 

- [ ] Java
- [ ] .NET
- [ ] Node
- [ ] PHP
- [ ] Python
- [ ] Go
- [ ] C

**Comment by MikeGoldsmith** [comment]
.NET SDK - http://review.couchbase.org/#/c/76953/

**Comment by daschl** [comment]
woops, need to add the type/keyword for each method

**Comment by daschl** [comment]
@griels @avsej please check your respective SDKs and let us know if this is good to be merged - thanks!

**Comment by daschl** [comment]
@griels it doesn't cover the sorting though, right?

**Comment by daschl** [comment]
@griels thanks for the heads up, then I'm going to close and merge it.

**Pull request merged**
