### PR TITLE
RFC10 FTS - Review Discussion

### PR DESCRIPTION
**Pull request by simonbasle**
This PR will ultimately move RFC10 (#17) to ACCEPTED state.
The intent for it is to centralize discussion raised during the REVIEW phase, and changes these discussions cause to the rfc.

### CODE REVIEW

**Comment by simonbasle** [comment]
These points were raised by @mschoch

- [ ] I strongly prefer "Query String Query" over "String Query".  I know it sounds redundant, but it is accepted terminology: See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html
- [ ] Boolean Field Query says something about "which can reduce index size" which I don't understand.
- [ ] Bleve API does not actually require the style in the highlight request, so "highlight": {} is valid, and uses the default highlighter.  It's not clear if this is just an intentional choice in the SDKs or oversight.
- [ ] Facet size/limit applies to all facets, but is documented in line about Term Facets
- [ ] Document says that all ranges values are inclusive, but this is not correct.  All ranges are inclusive on the lower bound, and exclusive on the upper bound.  Either boundary is optional, but you must specify at least one. Ranges may overlap, though applications should expect documents to be counted in multiple buckets when this is done.

(will be checked as these are resolved by RFC modifications or comments)

- [ ] UPDATE - date query no longer supports changing the date/time parser (need to verify this in 4.5)
  -  [ ] ⚠️ this needs a follow-up
- [ ] field section of wildcard query says it can affect analyzer user, but wildcard query does not use analyzer, same for date range query, numeric range query, regexp query, prefix query
- [ ] search result also can be 412 (precondition failed), this is returned when the requested consistency level could not be satisfied before the timeout was reached

**Comment by simonbasle** [comment]
@couchbaselabs/sdk-team as per Marty's comments, a few changes to the RFC that would warrant changes to the implementations: StringQuery, HTTP 412 error case, highlight style optional.

(the "Reword some pieces per Marty comments" commit doesn't imply implementation changes, unlike what's said in message)

**Comment by ingenthr** [comment]
Each SDK needs to check implementations w.r.t. recent updates:

- [ ] Java
- [ ] .NET
- [ ] Node
- [ ] PHP
- [ ] Python
- [ ] Go
- [ ] C

@couchbaselabs/sdk-team Need everyone to check implementations and check the box please!

**Comment by brett19** [comment]
Hey Simon,
Would it be possible to include the necessary handling details for error 412 in the RFC?
Cheers, Brett

**Comment by simonbasle** [comment]
There should be details in the error section of the document, as visible in
the pull request.

**Comment by daschl** [comment]
@couchbaselabs/sdk-team  heads up! 🔥 a new section on "sort" has been added which is coming in 4.6. 

- [] Java
- [ ] .NET
- [] Node
- [ ] PHP
- [ ] Python
- [] Go
- [ ] C

**Comment by daschl** [comment]
Alright! this looks good, I'll rebase and get this merged as ACCEPTED.

**Comment by avsej** [comment]
For FTS sorting in PHP I opened a [ticket], otherwise PHP is good on this change

[ticket]: https://issues.couchbase.com/browse/PCBC-469

**Comment by simonbasle** [comment]
heyo! glad to see this moving forward :D
it should probably be assigned to someone else though... RFC10, codename "hot potatoe" :rofl:

**Comment by daschl** [comment]
@simonbasle haha thanks didn't realize you were still assigned. I did pick it up and it looks like we can finally drive it to completion ;)

**Pull request merged**
