### PR TITLE
0001-rfc-process

### LINKED ISSUE #3: 0001-rfc-process
This RFC describes the newly established RFC process.

(how meta!)

### PR DESCRIPTION
**Pull request by daschl**
resolves #3

### CODE REVIEW

**Comment by daschl** [comment]
@couchbaselabs/sdk-team here is the proper pull request with the branching.

Let's do the final round of discussion so we can get this set up!

**Comment by daschl** [comment]
Since it came up in our last meeting, I ask everyone for a final :+1: or comments before we merge it in! Lets give us all the end of week deadline so it doesn't slip any longer.

ping @couchbaselabs/sdk-team

**Comment by daschl** [comment]
:+1:

**Comment by simonbasle** [comment]
:+1:

**Comment by daschl** [comment]
@brett19 @mnunberg @ingenthr @avsej @jeffrymorris  @ToddGreenstein

**Comment by mnunberg** [comment]
:+1:

**Comment by brett19** [comment]
:+1:

**Comment by jeffrymorris** [comment]
+1

**Comment by avsej** [comment]
looks good :+1:, although I would prefer gerrit for voting squashing etc

**Comment by daschl** [comment]
Alright, I'll get this merged in then.

**Pull request merged**
