### PR TITLE
Adding highlighted examples for Java/.NET

### PR DESCRIPTION
**Pull request by simonbasle**
Also highlighted the Python and C examples according to Github Flavored
Markdown syntax.

### CODE REVIEW

**Comment by simonbasle** [comment]
@jeffrymorris can you check the .NET example see if you spot inconsistencies? The subdoc commit in Gerrit is very light and doesn't even show the `IDocumentFragment` nor its implementation, and I'm not sure what you had in mind for the `MutateIn`/`LookupIn` syntax.

I think it would make sense to have the cas and expiry provided through the `IDocumentFragment`, wdyt?

**Comment by simonbasle** [comment]
cc. @mnunberg

**Comment by mnunberg** [comment]
I'm going to merge this now.. if there are any modifications they can be posted in a subsequent PR. In particular I do like the `getIn<T>` - it looks very elegant

**Comment by mnunberg** [comment]
Oh, and you can put names other than `mnunberg` if needed or desired :) - I just put it there as a dummy user!

**Comment by simonbasle** [comment]
@jeffrymorris please still have a look and follow up with a PR on the .NET code if you feel necessary (or send me comments).

**Pull request merged**
